FeedRefresherTask:
  cron: "7,17,27,37,47,57 * * * *"
  class: "FeedRefresher"
  queue: feed_refresher
  description: "This task will will refresh the feeds list 17 minutes after the start of every hour"
